import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-900 text-white p-4 flex items-center justify-between">
          <a href="/" className="flex items-center space-x-2">
            <img src="/logo.png" alt="Logo" className="h-12 w-12" />
            <span className="font-semibold text-lg">Mi Island</span>
          </a>

          <div className="space-x-4">
            <a href="/products" className="hover:underline">Products</a>
            <a href="/contact" className="hover:underline">Contact Us</a>
          </div>
        </nav>

        {/* Page content here */}
        <main className="p-4">
          {children}
        </main>
        <footer className="bg-gray-100 text-sm text-center p-4 mt-10">
          <p>
            Email: <a href="mailto:example@email.com" className="underline">example@email.com</a>
          </p>
          <p>Phone: 123-456-7890</p>
          <p>Address: 123 Main St, Brooklyn, NY</p>

          <div className="flex justify-center mt-3">
            <a
              href="https://www.xiaohongshu.com/user/profile/66620ebc0000000007004f5d?xsec_token=ABomhyhueLoVDm7pDOj3xeqEM7NuL8fhdd86MxT6BnQkY%3D&xsec_source=pc_search"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:opacity-80 transition"
            >
              <img
                src="/RedNote_logo.png"
                alt="小红书 Logo"
                className="w-16 h-6 object-contain rounded"
              />
            </a>
          </div>
        </footer>

      </body>
    </html>
  );
}
